org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# 1. Enable parallel and configuration cache after upgrading Kotlin
org.gradle.parallel=false
org.gradle.configuration-cache=false

# Prevent state lock issues in KGP
kotlin.parallel.tasks.in.project=false
kotlin.incremental=false

# 2. Настройки для Chaquopy и AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true
android.lint.useK2Uast=false
android.suppressUnsupportedCompileSdk=36
chaquopy.buildPython=python.exe