package com.example.videodownloader

import android.content.Context
import android.net.Uri
import android.webkit.CookieManager
import android.webkit.WebStorage
import java.io.File

object AuthManager {

    /**
     * Проверяет статус авторизации для YouTube (проверяет все возможные ключи сессий Google/YouTube)
     */
    private fun isYoutubeLoggedIn(): Boolean {
        val cm = CookieManager.getInstance()
        val urls = listOf("https://www.youtube.com", "https://m.youtube.com", "https://youtube.com", "https://accounts.google.com")
        val keys = listOf("LOGIN_INFO", "SAPISID", "SSID", "SID", "__Secure-3PAPISID", "__Secure-1PAPISID", "__Secure-3PSID", "APISID", "HSID")
        for (url in urls) {
            val cookies = cm.getCookie(url) ?: continue
            if (keys.any { key -> cookies.contains(key) }) {
                return true
            }
        }
        return false
    }

    /**
     * Проверяет статус авторизации для всех платформ
     */
    fun checkLoginStates(): Map<String, Boolean> {
        val cookieManager = CookieManager.getInstance()

        fun hasKey(url: String, key: String): Boolean {
            return cookieManager.getCookie(url)?.contains(key) == true
        }

        return mapOf(
            "ig" to hasKey("https://www.instagram.com", "sessionid"),
            "vk" to (hasKey("https://vk.com", "remixsid") || hasKey("https://id.vk.com", "remixsid") || hasKey("https://vkvideo.ru", "remixsid")),
            "yt" to isYoutubeLoggedIn(),
            "tt" to (hasKey("https://www.tiktok.com", "sessionid") || hasKey("https://www.tiktok.com", "sessionid_ss") || hasKey("https://www.tiktok.com", "sid_tt"))
        )
    }

    /**
     * ⚡ ПОЛНОЕ УНИЧТОЖЕНИЕ СЕССИЙ ДЛЯ КОНКРЕТНОЙ ПЛАТФОРМЫ
     */
    fun clearCookiesForPlatform(platformId: String) {
        val cookieManager = CookieManager.getInstance()

        // Стираем HTML5 WebStorage и базы данных токенов
        try {
            WebStorage.getInstance().deleteAllData()
        } catch (e: Exception) {
            e.printStackTrace()
        }

        val targetUrls = when (platformId) {
            "yt" -> listOf(
                "https://www.youtube.com",
                "https://m.youtube.com",
                "https://youtube.com",
                "https://accounts.google.com",
                "https://myaccount.google.com",
                "https://www.google.com",
                "https://google.com"
            )
            "ig" -> listOf(
                "https://www.instagram.com",
                "https://instagram.com",
                "https://accountscenter.instagram.com",
                "https://www.facebook.com"
            )
            "vk" -> listOf(
                "https://vk.com",
                "https://m.vk.com",
                "https://id.vk.com",
                "https://login.vk.com",
                "https://vkvideo.ru",
                "https://m.vkvideo.ru"
            )
            "tt" -> listOf(
                "https://www.tiktok.com",
                "https://tiktok.com",
                "https://auth.tiktok.com"
            )
            else -> return
        }

        for (url in targetUrls) {
            val cookiesStr = cookieManager.getCookie(url)
            if (!cookiesStr.isNullOrBlank()) {
                val cookies = cookiesStr.split(";")
                val host = Uri.parse(url).host ?: ""
                val rootDomain = if (host.startsWith("www.")) host.substring(4) else host

                for (cookie in cookies) {
                    val cookieName = cookie.substringBefore("=").trim()
                    if (cookieName.isNotEmpty()) {
                        cookieManager.setCookie(url, "$cookieName=; Expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/")
                        cookieManager.setCookie(url, "$cookieName=; Expires=Thu, 01 Jan 1970 00:00:01 GMT; domain=$host; path=/")
                        cookieManager.setCookie(url, "$cookieName=; Expires=Thu, 01 Jan 1970 00:00:01 GMT; domain=.$rootDomain; path=/")
                        cookieManager.setCookie(url, "$cookieName=; Expires=Thu, 01 Jan 1970 00:00:01 GMT; domain=$rootDomain; path=/")
                    }
                }
            }
        }
        cookieManager.flush()
    }

    /**
     * Экспортирует куки в стандартный Netscape-формат для yt-dlp
     */
    fun exportCookies(context: Context): File? {
        val appContext = context.applicationContext
        val cookieManager = CookieManager.getInstance()
        val cookieFile = File(appContext.cacheDir, "yt_dlp_cookies.txt")

        try {
            val stringBuilder = java.lang.StringBuilder()
            stringBuilder.append("# Netscape HTTP Cookie File\n")
            stringBuilder.append("# Generated by Videx App\n\n")

            var hasCookies = false
            val seenCookies = mutableSetOf<String>()
            val googleAuthCookies = mutableMapOf<String, String>()

            val cookieSources = listOf(
                ".youtube.com" to listOf("https://www.youtube.com", "https://m.youtube.com", "https://youtube.com"),
                ".google.com" to listOf("https://accounts.google.com", "https://myaccount.google.com", "https://www.google.com"),
                ".tiktok.com" to listOf("https://www.tiktok.com", "https://m.tiktok.com", "https://tiktok.com", "https://auth.tiktok.com"),
                ".vk.com" to listOf("https://vk.com", "https://m.vk.com", "https://id.vk.com", "https://login.vk.com"),
                ".vkvideo.ru" to listOf("https://vkvideo.ru", "https://m.vkvideo.ru", "https://vk.com"),
                ".instagram.com" to listOf("https://www.instagram.com", "https://instagram.com", "https://m.instagram.com")
            )

            for ((domain, sourceUrls) in cookieSources) {
                for (sourceUrl in sourceUrls) {
                    val cookiesStr = cookieManager.getCookie(sourceUrl)
                    if (!cookiesStr.isNullOrBlank()) {
                        val cookiePairs = cookiesStr.split(";")
                        for (pair in cookiePairs) {
                            if (pair.contains("=")) {
                                val parts = pair.trim().split("=", limit = 2)
                                if (parts.size == 2) {
                                    val name = parts[0].trim()
                                    val value = parts[1].trim()
                                    val dedupeKey = "${domain}_$name"

                                    if (domain == ".google.com" || domain == ".youtube.com") {
                                        googleAuthCookies[name] = value
                                    }

                                    if (name.isNotBlank() && !seenCookies.contains(dedupeKey)) {
                                        stringBuilder.append("$domain\tTRUE\t/\tTRUE\t2147483647\t$name\t$value\n")
                                        seenCookies.add(dedupeKey)
                                        hasCookies = true
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // 🧠 КРИТИЧЕСКИЙ БУСТ ДЛЯ YT-DLP: Дублируем сессионные куки Google на домен .youtube.com
            for ((name, value) in googleAuthCookies) {
                val ytDedupeKey = ".youtube.com_$name"
                if (!seenCookies.contains(ytDedupeKey)) {
                    stringBuilder.append(".youtube.com\tTRUE\t/\tTRUE\t2147483647\t$name\t$value\n")
                    seenCookies.add(ytDedupeKey)
                    hasCookies = true
                }
            }

            if (hasCookies) {
                cookieFile.writeText(stringBuilder.toString())
                AsyncLogger.log(LogLevel.INFO, "Куки экспортированы (${seenCookies.size} шт.): ${cookieFile.absolutePath}")
                return cookieFile
            }
        } catch (e: Exception) {
            AsyncLogger.log(LogLevel.ERROR, "Ошибка экспорта куки: ${e.message}")
        }
        return null
    }

    fun clearAllCookies() {
        try {
            WebStorage.getInstance().deleteAllData()
        } catch (e: Exception) {
            e.printStackTrace()
        }
        CookieManager.getInstance().removeAllCookies(null)
        CookieManager.getInstance().flush()
    }
}
